---
- name: Append new noproxy in containerd systemd config
  hosts: all
  become: true
  vars_prompt:
    - name: "host"
      prompt: "New noproxy host"
      private: false
  tasks:
    - name: Append new noproxy in containerd systemd config
      ansible.builtin.lineinfile:
        path: /etc/systemd/system/containerd.service.d/http-proxy.conf
        line: 'Environment="NO_PROXY=$NO_PROXY,{{ host }}"'
      notify: restart containerd

  handlers:
    - name: restart containerd
      ansible.builtin.systemd:
        name: containerd
        state: restarted