---
- name: Generate ed25519 SSH key pair if directory and file do not exist
  hosts: localhost

  vars:
    sshKeyPath: /root/.ansible/.ssh/id_ed25519

  tasks:
    - name: Extract SSH key directory
      set_fact:
        sshKeyDir: "{{ sshKeyPath | dirname }}"

    - name: Check if SSH key directory exists
      stat:
        path: "{{ sshKeyDir }}"
      register: ssh_key_dir

    - name: Create SSH key directory
      file:
        path: "{{ sshKeyDir }}"
        state: directory
        mode: '0700'
      when: not ssh_key_dir.stat.exists

    - name: Check if SSH key file exists
      stat:
        path: "{{ sshKeyPath }}"
      register: ssh_key_file

    - name: Generate SSH key pair
      command: ssh-keygen -t ed25519 -f "{{ sshKeyPath }}" -q -N ''
      when: not ssh_key_file.stat.exists
