- name: Disable localhost DNS
  hosts: all
  become: true
  tasks:
    - name: Remove /etc/resolv.conf symlink
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent
    - name: Create new symlink to /run/systemd/resolve/resolv.conf
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
