# Pre-installation k8s nodes playbook

# Disable swap play
- name: Disable SWAP
  hosts: all
  become: yes
  tasks:
  - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
    shell: |
      swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
    mount:
      name: swap
      fstype: swap
      state: absent

- name: Set timezone to Asia/Tehran
  hosts: all
  become: yes
  tasks:
  - name: Set timezone to Asia/Tehran
    timezone:
      name: Asia/Tehran
