---
- name: Create .ssh/config file from YAML inventory
  hosts: kube_lb
  vars:
    ssh_port: " {{ ssh_port_initial }}"
      #ssh_port: " {{ ssh_port_desired }}"
      # desired is 23389 | initial is 22
      # check inventory for refrence
  tasks:
    - name: Create .ssh directory if it doesn't exist
      file:
        path: "{{ ssh_config_dir }}"
        state: directory
        mode: '0700'

    - name: Create .ssh/config file
      copy:
        content: |
          {% for host in groups['all'] %}
          {% set hostvars = hostvars[host] %}
          {% if 'ip' in hostvars %}
          Host {{ host }}
            HostName {{ hostvars.ip }}
            User {{ ssh_user }}
            Port {{ ssh_port }}
            IdentityFile {{ ssh_identity_file }}
          {% endif %}
          {% endfor %}
        dest: "{{ ssh_config_path }}"
        mode: '0600'

